Repository microsoft/mu_feature_dfci, pull requests merged in 2023-04, with the labels that each got.

#70 Revert VarPolicy locking change
  DfciPkg/DfciManager/DfciManager.h
  DfciPkg/DfciManager/DfciManager.inf
  DfciPkg/DfciManager/DfciVarPolicies.c
  DfciPkg/DfciPkg.dec
  DfciPkg/Include/Guid/DfciInternalVariableGuid.h
  DfciPkg/Include/Private/DfciVariablePolicies.h
  DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTest.c
  DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciVarLockAuditTestApp.inf
Labels: urgency:high, type:design-change, type:bug, impact:security, complexity:intermediate

#73 Fix duplicate name error when adding second firewall rule
  DfciPkg/UnitTests/DfciTests/DeviceUnderTest/SetupDUT.ps1
Labels: impact:testing

#76 Remove references to a function removed long ago
  DfciPkg/IdentityAndAuthManager/AuthManagerProvision.c
  DfciPkg/Library/DfciUiSupportLibNull/DfciUiSupportLibNull.c
Labels: impact:non-functional

#84 Dfci support for using a QemuQ35Pkg virtual system as the device under test
  DfciPkg/DfciPkg.ci.yaml
  DfciPkg/Docs/QemuQ35Pkg/ReadMe.md
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/BootConfiguration.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/ChangeSecureBoot.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/FrontPage.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/InitialState.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/ManagementChanged.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/ManagementOptedIn.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/ManagementOptedOut.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/SecureBootOff.png
  DfciPkg/Docs/QemuQ35Pkg/ScreenShots/SecureBootOn.png
  DfciPkg/UnitTests/DfciTests/RefreshServer/Src/DfciTests.ini
  DfciPkg/UnitTests/DfciTests/Support/Python/DFCI_SupportLib.py
  DfciPkg/UnitTests/DfciTests/Support/Python/PyRobotRemote.py
  DfciPkg/UnitTests/DfciTests/Support/Python/SettingsXMLLib.py
  DfciPkg/UnitTests/DfciTests/Support/Robot/DFCI_Shared_Keywords.robot
  DfciPkg/UnitTests/DfciTests/Support/Robot/DFCI_Shared_Keywords2.robot
  DfciPkg/UnitTests/DfciTests/Support/Robot/DFCI_Shared_Paths.robot
  DfciPkg/UnitTests/DfciTests/Support/Robot/DFCI_VariableTransport.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_CertChainingTest/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneBadUpdate/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneEnroll/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTunePermissions/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneRollCerts/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneSettings/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneUnenroll/DfciSettings2.xml
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InTuneUnenroll/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_InitialState/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_RefreshServer/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_TPM_DisableEnable/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/DFCI_UnsignedSettings/run.robot
  DfciPkg/UnitTests/DfciTests/TestCases/QuickTest/run.robot
  DfciPkg/UnitTests/DfciTests/pip-requirements.txt
  DfciPkg/UnitTests/DfciTests/readme.md
Labels: type:documentation, language:python, impact:non-functional, impact:breaking-change, impact:testing
