Repository microsoft/mu_feature_dfci, pull requests merged in 2023-02, with the labels that each got.

#15 .azurepipelines: Add support for new artifacts_identifier param
  .azurepipelines/Matrix-Build-Job.yml
Labels: type:enhancement, impact:non-functional, impact:breaking-change

#2 Update document links to point into mu_feature_dfci
  DfciPkg/Docs/Dfci_Feature.md
  DfciPkg/Docs/Internals/DfciInternals.md
  DfciPkg/Docs/PlatformIntegration/DfciGroups.md
  DfciPkg/Docs/PlatformIntegration/PlatformIntegrationOverview.md
  DfciPkg/Docs/Scenarios/DfciScenarios.md
  DfciPkg/Library/DfciSampleProvider/readme.md
  RepoDetails.md
Labels: type:documentation, impact:non-functional

#23 Update DfciVarLock to correctly lock Dfci Variables
  DfciPkg/DfciManager/DfciManager.inf
  DfciPkg/DfciManager/DfciVarPolicies.c
  DfciPkg/DfciPkg.dec
  DfciPkg/Include/Guid/DfciInternalVariableGuid.h
  DfciPkg/Include/Private/DfciVariablePolicies.h
  DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTest.c
  DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciVarLockAuditTestApp.inf
Labels: bug, impact:testing, impact:security

#31 DfciPkg/UiSupport: Fix bad size in memory alloc
  DfciPkg/IdentityAndAuthManager/UiSupport.c
Labels: type:bug

#24 DfciPkg: Additional CodeQL fixes
  DfciPkg/Application/DfciMenu/DfciRequest.c
  DfciPkg/Application/DfciMenu/DfciUpdate.c
  DfciPkg/IdentityAndAuthManager/UiSupport.c
  DfciPkg/Library/DfciSettingPermissionLib/DfciSettingPermissionProvisioned.c
  DfciPkg/SettingsManager/SettingsManagerCurrentSettingXml.c
  DfciPkg/SettingsManager/SettingsManagerProvider.c
  DfciPkg/SettingsManager/SettingsManagerTransportXml.c
Labels: impact:security

#4 Minor changes to Readme.rst
  Readme.rst
Labels: type:documentation, impact:non-functional

#35 .pytool/CISettings.py: Use all CodeQL filter files
  .pytool/CISettings.py
Labels: impact:non-functional

#39 Update lock test pass message to avoid confusion
  DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTest.c
  DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTestXml.c
  DfciPkg/UnitTests/DfciVarLockAudit/UEFI/DfciLockTestXml.h
Labels: type:bug, impact:testing, complexity:easy
