Repository microsoft/mu_feature_dfci, pull requests merged in 2023-03, with the labels that each got.

#48 Refactor ProviderValueAsAscii()
  DfciPkg/Include/DfciSystemSettingStrings.h
  DfciPkg/SettingsManager/SettingsManager.h
  DfciPkg/SettingsManager/SettingsManagerCurrentSettingXml.c
  DfciPkg/SettingsManager/SettingsManagerProvider.c
Labels: type:bug

#53 DfciPkg: More CodeQL fixes
  DfciPkg/Application/DfciMenu/DfciMenu.c
  DfciPkg/DfciPkg.dsc
Labels: impact:security

#61 Revert invalid change which breaks DFCI Refresh from network from "Add Test requirement for using local Refresh from Network server. (#3)" 577c811
  DfciPkg/Application/DfciMenu/DfciRequest.c
Labels: semver:minor, type:bug

#64 Make DFCI Lock Var Runtime accessible
  DfciPkg/Include/Guid/DfciInternalVariableGuid.h
Labels: semver:minor, type:bug, impact:security
