Repository microsoft/mu_feature_dfci, pull requests merged in 2024-01, with the labels that each got.

#181 Add missing library header guards
  DfciPkg/Include/Library/DfciAssetTagSettingLib.h
  DfciPkg/Include/Library/DfciGroupLib.h
  DfciPkg/Include/Library/DfciSettingChangedNotificationLib.h
  DfciPkg/Include/Library/DfciV1SupportLib.h
Labels: impact:non-functional

#182 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: semver:patch, impact:non-functional

#190 Update pip-requirements.txt
  pip-requirements.txt
Labels: type:dependencies, impact:non-functional
